name: Deploy Docker

on:
  create:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Publish Compiler
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: kmruiz/sonata
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        dockerfile: Dockerfile
        tags: latest,${GITHUB_REF##*/}
    - name: Publish Playground
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: kmruiz/sonata
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        dockerfile: Dockerfile
        tags: playground,playground_${GITHUB_REF##*/}
