name: Deploy Docker

on:
  create:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
    - name: Publish Compiler
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: kmruiz/sonata
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        dockerfile: Dockerfile
        tags: latest,${{ env.RELEASE_VERSION }}
    - name: Publish Playground
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: kmruiz/sonata
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        dockerfile: Dockerfile_playground
        tags: playground,playground_${{ env.RELEASE_VERSION }}
